//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyProgrammerTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DailyProgrammerTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;time&quot;:1595873990,&quot;states&quot;:[[&quot;4cc386&quot;,&quot;TFSAL   &quot;,&quot;Iceland&quot;,1595873866,1595873869,-21.5967,63.9932,944.88,false,20.49,28.5,-0.33,null,null,null,false,0],[&quot;a425dd&quot;,&quot;N36664  &quot;,&quot;United States&quot;,1595873989,1595873989,-112.1905,33.362,800.1,false,81.24,334.9,-1.3,null,784.86,&quot;3304&quot;,false,0],[&quot;4b1812&quot;,&quot;SWR170X &quot;,&quot;Switzerland&quot;,1595873989,1595873989,9.6261,53.1268,6355.08,false,199.38,190.56,9.75,null,6560.82,&quot;1105&quot;,false,0],[&quot;abd9d9&quot;,&quot;SWA1727 &quot;,&quot;United States&quot;,1595873985,1595873986,-112.3749,36.3898,11894.82,false, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AeroPlaneInfo {
            get {
                return ResourceManager.GetString("AeroPlaneInfo", resourceCulture);
            }
        }
    }
}
